backend = "glx";
vsync = true;

corner-radius = 8;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

shadow = false;

opacity-rule = [
  "90:class_g = 'Alacritty' && focused",
  "85:class_g = 'Alacritty' && !focused"
];

animations = (
  {
    triggers = [ "open", "show" ];

    opacity = {
      curve = "cubic-bezier(0.23, 1, 0.32, 1)";
      duration = 0.18;
      start = 0;
      end = 1;
    };

    scale-x = {
      curve = "cubic-bezier(0.175, 0.885, 0.32, 1.15)";
      duration = 0.22;
      start = 0.92;
      end = 1;
    };

    scale-y = "scale-x";

    shadow-opacity = "opacity";
    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
  },
  {
    triggers = [ "close", "hide" ];

    opacity = {
      curve = "cubic-bezier(0.65, 0.05, 0.36, 1)";
      duration = 0.14;
      start = 1;
      end = 0;
    };

    scale-x = {
      curve = "cubic-bezier(0.65, 0.05, 0.36, 1)";
      duration = 0.16;
      start = 1;
      end = 0.94;
    };

    scale-y = "scale-x";

    shadow-opacity = "opacity";
    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
  }
);
