[general]
import = ["catppuccin-mocha.toml"]

[window]
startup_mode = "Maximized"

[font]
size = 12

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Medium"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "PageUp"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "PageDown"
action = "ScrollLineDown"
