#!/usr/bin/env bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width 4
bspc config window_gap 4
bspc config top_padding 2
bspc config bottom_padding 2
bspc config left_padding 2
bspc config right_padding 2

bspc config normal_border_color "#45475A"
bspc config active_border_color "#7F849C"
bspc config focused_border_color "#89B4FA"
bspc config presel_feedback_color "#F9E2AF"

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true

bspc rule -a '*' state=tiled
