position = "top"
height = 32

[[start]]
type = "workspaces"

[[start]]
type = "label"
name = "spacer"
label = ""

[[start]]
type = "focused"
icon_size = 20

[start.truncate]
mode = "end"
max_length = 64

[[end]]
type = "volume"

[[end]]
type = "brightness"

[[end]]
type = "battery"
icon_size = 16

[[end]]
type = "clock"
format = "%d-%b-%Y %I:%M:%S%P"
